### ISSUE TITLE
Default value for `tag` does not work

### ISSUE THREAD

**Issue by sja** [gvalkov/jenkins-autojobs#18]
My configuration contains this:

``` yaml
        # Does not work
        tag: 'myRepoOne'
        refs:
          - 'refs/heads/feature_(.*)'
```

But that does not use the tag on creating jobs. I had to put a `tag` on the ref config:

``` yaml
        # Works
        tag: 'myRepoOne'
        refs:
          - 'refs/heads/feature_(.*)'
              'tag': 'myRepoOne'
```
